### PR TITLE
Switch to Hatch for build

### PR DESCRIPTION
**Pull request by turnerm**
Hi Mike,

Here is a first stab at migrating to Hatch. Marking as draft for now because I need to figure out why the tests don't work, and also there are a couple of oustanding items from the `setuptools` settings, that I need to ask you about:

1. `zip-safe`: I couldn't find much info on this for Hatch, is there a reason why you require it?
2. `include-package-data`: I believe whatever needs to be included should just be added explicitly, what should be included other than `src`? 

For the namespaces, I found [this](https://hatch.pypa.io/latest/config/build/#packages) so I think nothing needs to be set explicitly.

And as for the version attribute, which was set explicitly in the project metadata, I believe that can be omitted.

### CODE REVIEW

**Comment by mcarans** [comment]
1. I think that zip_safe was there for historic reasons and can be removed: https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html
2. I set include_package_data to be True across all libraries although it is only really needed for some eg. HDX Python Country which have data files under the src folder. These get included by setuptools_scm because they are in the Git repo. Setting include_package_data to be True when there aren't any data files under src doesn't cause any problems. The only way setting it True might be problematic is if there are data files under src in the Git repo that shoud not be included.
https://setuptools.pypa.io/en/latest/userguide/datafiles.html 

I'm not sure regarding the project version in the project metadata. It was needed for setuptools_scm, but if it works without in hatch-vcs, all the better.

Would you also be able to look at replacing tox with hatch as a test runner (either in this PR or separately if you prefer)? I came across this [PR](https://github.com/mkdocs/mkdocs/pull/2991) from another project where they migrated from tox to hatch and also found an example in [Hatch FAQ](https://hatch.pypa.io/latest/meta/faq/#environments).

**Comment by turnerm** [comment]
For point #2 I'm guessing that [include](https://hatch.pypa.io/latest/config/build/#patterns) should work, will add it into `hdx-python-country` when the time comes.

> Would you also be able to look at replacing tox with hatch as a test runner 
Ah great point, will do in this PR!

**Comment by turnerm** [comment]
Hey @mcarans, ah sorry this is taking so long, but need to iterate with you over a couple of points:

1. The test dependencies. I'm unfortunately not able to find a way for `hatch` to read in a requirements file for the tests.  ([this library](https://pypi.org/project/hatch-requirements-txt/) is for using a requirements file for the source package, not for other environments). At the moment, I've hardcoded the test requirements [here](https://github.com/OCHA-DAP/hdx-python-utilities/pull/15/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R35) but I don't think that's a good solution. Something that could work, which we've done for [anticipy](https://github.com/OCHA-DAP/ocha-anticipy/tree/develop), is to make `test` [one of the extras](https://github.com/OCHA-DAP/ocha-anticipy/blob/develop/setup.cfg#L71). And for a pinned requirements file, we generate that with [`pip-tools` run with `pre-commit`](https://github.com/OCHA-DAP/ocha-anticipy/blob/develop/.pre-commit-config.yaml#L48).  I'd be interested to know what you think, of course `autohooks` changes things a bit, which also leads me to my next question. 

2. In the past, how have you been using `autohooks` -- just `pip install autohooks` in your personal virtual environment and it should run automatically when you commit? What is the reason for having [a linting environment](https://github.com/OCHA-DAP/hdx-python-utilities/blob/main/pyproject.toml#L46) in `tox`? Also, has it been working for you? For example if I run `flake8 --color=always src tests` in the top-level directory I get perhaps 100 errors, all complaining that lines are too long.

**Comment by mcarans** [comment]
No problem. I didn't think it would be straightforward - packaging in Python never is lol. 

My general goal with the setup is that it works well with PyCharm (and PyCharm's limitations), minimises what needs to be done on the command line and is easy to duplicate to all the other libraries (hence why I found it convenient to have as much as possible in pyproject.toml).

1. The reason I have the requirements file is mainly because it's easier to set up PyCharm (PyCharm cannot read from pyproject.toml). I have requested Hatch support in PyCharm and others have requested pyproject.toml support a long time ago - I'm not sure when any of that will see the light of day. 

You mentioned pip-tools and I see that it specifically supports Hatch which is a big plus so could read the dependencies from `[project.optional-dependencies]` . I guess it's then possible to set up pip-tools to generate a test-requirements.txt that PyCharm can use?

I have been reluctant to use pre-commit because it requires its own separate configuration files hence why I looked at autotools which supports pyproject.toml. 

An alternative to trying to put everything into pyproject.toml is to have configuration files all in a folder like `.config` but some tools insist on their configuration file being in the root.

2. I have only begun experimenting with autohooks and so it is only in HDX Python Utilities. I think you will need to activate it once installed in local virtualenv with `autohooks activate --mode pythonpath`. However, I note that it doesn't support pip-tools at the moment. 

The tox lint workflow is run by GitHub Actions eg. [here](https://github.com/OCHA-DAP/hdx-python-utilities/actions/runs/4694228809/jobs/8322175914). The reason you see errors locally is because flake8 doesn't recognise pyproject.toml by default. The tox lint workflow uses the flake8 plugin flake8-pyproject. If you install that dependency, the errors will go away.

3. It could be that the httpbin site which I am using to test post requests is now blocking the GitHub Actions server. You can ignore the error for now.

It may be that the tooling is not all there yet and we have to wait a bit. My thinking is that if there are issues against different tools to solve the setup puzzle satisfactorily in different ways, then hopefully one of them will come to fruition! 
You can create issues for the missing components against the appropriate tools. For example, if you think that migrating from tox to Hatch for test running is a problem due to the inability to read test-requirements.txt (and there isn't another way to solve the problem so that PyCharm can be set up easily), you could create an issue for hatch-requirements to add support for syncing development/test requirements and we can wait to see what happens.

BTW, if you think of better ways to achieve what I put above as the "general goal", please feel free to experiment.

**Comment by turnerm** [comment]
@mcarans thanks so much for the detailed response. 

Agree about keeping the `requirements.txt`, I find it very handy for projects to have them. 

I think there is definitely a solution, it would involve `pre-commit` (for `pip-tools`) but I can try to put as much as possible into a `.config` directory. 

A couple of more points about #2:
- Is there not a bit of redundancy running the linter both as a git hook, and then in github actions? One could argue that the latter is a failsafe in case a developer forgot to setup the hooks, but I am just curious what's your motivation.
- FYI, at the moment I don't have the linter running in GitHub Actions on this branch, but I can change that. However unlike in tox, I _think_ I will need to set that up directly in the GitHub actions config file - I can't find a `tox-gh-actions` equivalent.

**Comment by mcarans** [comment]
@turnerm It would be helpful to have linting in GitHub Actions as should we have PRs from non-Centre people (like I had for HDX Python Country), it would be good to know that they are linted properly. 

One example of linting I came across is Hatch's own GitHub Actions [test workflow](https://github.com/pypa/hatch/blob/master/.github/workflows/test.yml#L46-L48) and [hatch.toml](https://github.com/pypa/hatch/blob/master/hatch.toml#L47-L68). It uses a [detached environment](https://hatch.pypa.io/latest/config/environment/overview/#detached-environments) in Hatch which says "A common use case is standalone environments that do not require inheritance nor the installation of the project, such as for linting". I note that they use ruff for linting so if it is easier to just copy that setup, then we could consider switching from flake8 since that is something I had been considering anyway for the future.

**Comment by turnerm** [comment]
@mcarans so sorry for the delay, I think it's finally ready for review. Some things to note:

- I've added pre-commit, putting the config file in the `.config` directory. Because this makes the setup a bit more complicated, I added a `CONTRIBUTING.md` file, with some text inspired from AnticiPy. But let me know if you'd like that information changed / put elsewhere / etc. 
- I've merged to a single `requirements.txt` file, as the way things are setup now, the `dev` optional dependency actually contains all the test dependencies plus pre-commit, and that's what's used to create `requirements.txt`. I could instead generate `requirements.txt` from `all`, `requirements-test.txt` from `test`, and `requirementst-dev.txt` from `dev`, however I thought maybe it's overkill. Also, any bespoke requirements files would contain all package-related requirements, in addition to those needed for test / dev, because of the way it's set up in the configuration. We went through this process for `AnticiPy` and settled on having a single requirements file in the end - let me know what you think. 
- I haven't added back any of the doc building command that used to be in `tox`, are those needed?
- Most importantly, I have not tested the publish workflow, and I think I'll need you to update the GitHub secrets if we'd like to do so.

**Comment by turnerm** [comment]
@mcarans thanks for catching the issue with the requirements files. I've found a solution and honestly I like it better: the extra requirements are back to being stand-alone, and for the requirements file I just used a flag that installs all extras. But if you'd like the requirements files split up let me know of course.

**Review by mcarans — APPROVED** [review]
Sorry for the delay in checking this. It all looks good to me. I have not tested the publishing, but I think that needs to be done when the workflow is in the main branch (unless you know otherwise). I have approved and you can merge whenever you're ready.

**Pull request merged**
